<?php /** @var Magento\Framework\Escaper $escaper */ ?>

<div slot="groupCaption" class="groupCaption">{{group.name}}</div>
<ff-asn-group-element>
    <div slot="selected"><span class="filterName">{{{element.name}}}</span></div>
    <div slot="unselected"><span class="filterName">{{{element.name}}}</span></div>
</ff-asn-group-element>

<div data-container="detailedLinks"><div data-content="detailedLinks"></div></div>
<div data-container="hiddenLinks"><div data-content="hiddenLinks"></div></div>

<div data-container="removeFilter"><?= $escaper->escapeHtml(__('Remove Filter')) ?></div>
<div data-container="showMore"><span class="text"><?= $escaper->escapeHtml(__('Show More')) ?></span></div>
<div data-container="showLess"><span class="text"><?= $escaper->escapeHtml(__('Show Less')) ?></span></div>
