<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<div class="ff-asn">
    <ff-asn align="vertical" unresolved>
        <ff-asn-group for-group="all" class="cursor">
            <div slot="groupCaption" class="groupCaption">{{group.name}}</div>

            <ff-asn-group-element>
                <div slot="selected"><span class="filterName">{{element.name}}</span></div>
                <div slot="unselected"><span class="filterName">{{element.name}}</span></div>
            </ff-asn-group-element>

            <div data-container="detailedLinks"><div data-content="detailedLinks"></div></div>
            <div data-container="hiddenLinks"><div data-content="hiddenLinks"></div></div>

            <div data-container="removeFilter"><?= $block->escapeHtml(__('Remove Filter')) ?></div>
            <div data-container="showMore"><span class="text"><?= $block->escapeHtml(__('Show More')) ?></span></div>
            <div data-container="showLess"><span class="text"><?= $block->escapeHtml(__('Show Less')) ?></span></div>
        </ff-asn-group>

        <ff-asn-group-slider>
            <div slot="groupCaption" class="groupCaption">{{group.name}}</div>

            <ff-slider-control submit-on-input="true">
                <input data-control="1" style="position: absolute; width: 60px;left: 15px;top:12px;" />
                <input data-control="2" style="position: absolute; width: 60px;right: 15px;top:12px;" />

                <ff-slider current-min-value="0" style="width: 150px;margin-top: 30px;">
                    <div slot="slider1" id="slider1" class="sliderBtn"></div>
                    <div slot="slider2" id="slider2" class="sliderBtn"></div>
                </ff-slider>
            </ff-slider-control>

            <div data-container="removeFilter"><?= $block->escapeHtml(__('Remove Filter')) ?></div>
        </ff-asn-group-slider>
    </ff-asn>
</div>
