<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */

/** @var string $categoryPathFieldName */
$categoryPathFieldName = (string) $block->getData('category_path_field_name');
/** @var bool $isCategoryPage */
$isCategoryPage = (bool) $block->getData('is_category_page'); ?>

<div class="ff-asn">
    <ff-asn align="vertical" unresolved>
<!--        <ff-asn-group for-group="all" class="cursor">-->
<!--            --><?php //= $block->getChildHtml('factfinder.asn_group') ?>
<!--        </ff-asn-group>-->
<!---->
<!--        <ff-asn-group for-group="--><?php //= /* @noEscape */ $categoryPathFieldName ?><!--ROOT" --><?php //if($isCategoryPage):?><!-- class="hidden" --><?php //endif;?><!-->-->
<!--            --><?php //= $block->getChildHtml('factfinder.asn_group') ?>
<!--        </ff-asn-group>-->
<!---->
<!--        <ff-asn-group-slider>-->
<!--            <div slot="groupCaption" class="groupCaption">{{group.name}}</div>-->
<!---->
<!--            <ff-slider-control submit-on-input="true">-->
<!--                <input data-control="1" style="position: absolute; width: 60px;left: 15px;top:12px;" />-->
<!--                <input data-control="2" style="position: absolute; width: 60px;right: 15px;top:12px;" />-->
<!---->
<!--                <ff-slider current-min-value="0" style="width: 150px;margin-top: 30px;">-->
<!--                    <div slot="slider1" id="slider1" class="sliderBtn"></div>-->
<!--                    <div slot="slider2" id="slider2" class="sliderBtn"></div>-->
<!--                </ff-slider>-->
<!--            </ff-slider-control>-->
<!---->
<!--            <div data-container="removeFilter">--><?php //= $escaper->escapeHtml(__('Remove Filter')) ?><!--</div>-->
<!--        </ff-asn-group-slider>-->
    </ff-asn>
</div>
