<?php /** @var Magento\Framework\View\Element\Template $block */ ?>

<div class="ff-breadcrumb-trail">
    <span class="description"><?= $block->escapeHtml(__('Your search for:')) ?></span>

    <ff-breadcrumb-trail unresolved>
        <ff-breadcrumb-trail-item type="all">
            <span>{{text}}</span>
        </ff-breadcrumb-trail-item>
    </ff-breadcrumb-trail>

    <ff-template scope="result" unresolved>
        <span style="padding-left: 15px"><?= $block->escapeHtml(__('produced {{resultCount}} results')) ?></span>
    </ff-template>
</div>
