<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<div class="ff-breadcrumb-trail">
    <ff-breadcrumb-trail unresolved></ff-breadcrumb-trail>
    <ff-template scope="result" unresolved>
        <span class="description"><?= $block->escapeHtml(__('Your search for:')) ?></span>
        <?= $block->escapeHtml(__('produced <span>{{resultCount}}</span> results'), ['span']) ?>
    </ff-template>
</div>
