<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<ff-campaign-advisor unresolved>
    <ff-campaign-advisor-question>
        <span>
            <h1 data-question>{{{text}}}</h1>
        </span>
        <div>
            <ff-campaign-advisor-answer>
                <div>{{{text}}}</div>
            </ff-campaign-advisor-answer>
        </div>
    </ff-campaign-advisor-question>
</ff-campaign-advisor>
