<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Omikron\Factfinder\ViewModel\Communication $viewModel */
$viewModel  = $block->getViewModel();
$communicationParameters = (array) $block->getData('communication_parameters');
$parameters = $viewModel->getParameters($communicationParameters);
$searchImmediate = $communicationParameters['search-immediate'] ?? 'false';
?>
<ff-communication<?php foreach ($parameters as $key => $value) /* @noEscape */ echo sprintf(' %s="%s"', $key, $block->escapeHtmlAttr($value)) ?>></ff-communication>

<?php if ($viewModel->isSsrEnable()): ?>
    <script>
            function generateSid() {
                var length = 30;
                var characterSet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
                var text = "";
                for (var i = 0; i < length; i++) {
                    text += characterSet.charAt(Math.floor(Math.random() * characterSet.length));
                }
                return text;
            }

            const ffCookies = document.cookie.split('; ').reduce((acc, cookie) => {
                const cookieData = cookie.split('=');
                const [key, value] = cookieData;
                acc[key] = value;

                return acc;
            }, {});

            const ffcommunication = document.querySelector('ff-communication');

            if (!ffCookies['ffwebc_sid']) {
                const sid = generateSid();
                document.cookie = 'ffwebc_sid=' + sid + '; path=/;';
                ffcommunication.setAttribute('sid', sid);
            } else {
                ffcommunication.setAttribute('sid', ffCookies['ffwebc_sid']);
            }
    </script>
<?php endif; ?>

<!-- Set FieldRoles -->
<script>
    document.addEventListener('ffReady', function () {
        factfinder.sdk = 'm2-v4.2.2';
        factfinder.communication.fieldRoles = <?= /* @noEscape */ $viewModel->getFieldRoles() ?>;
    });
</script>

<script>
    document.addEventListener('ffCommunicationReady', ({ factfinder, searchImmediate }) => {
        const cookies = document.cookie.split('; ').reduce((acc, cookie) => {
            const cookieData = cookie.split('=');
            const [key, value] = cookieData;
            acc[key] = value;

            return acc;
        }, {});

        const clearCookie = (name) => {
            document.cookie = name+'=; Max-Age=-1;';
        }

        if (cookies['ff_user_id']) {
            factfinder.communication.sessionManager.setLoginData(cookies['ff_user_id'])

            if (cookies['ff_has_just_logged_in']) {
                clearCookie('ff_has_just_logged_in');
                factfinder.communication.Tracking.loginWithConfig();
            }
        } else {
            factfinder.communication.sessionManager.clearLoginData();

            if (cookies['ff_has_just_logged_out']) {
                clearCookie('ff_has_just_logged_out');
                factfinder.communication.sessionManager.clearAllSessionData();
            }
        }

        if (<?= /** @SuppressWarnings(PHPMD) */ $searchImmediate ?>) {
            searchImmediate();
        }
    });
</script>
