<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <ff-navigation unresolved layout="horizontal" flyout="true" mobile="false">
            <ff-navigation-item class="ff-nav-container">
                <li class="ff-navigation-item">
                    <a class="ffw-nav-link" onclick="event.preventDefault()" href="{{__TARGET_URL__.url}}">
                        {{name}}
                    </a>
                </li>
            </ff-navigation-item>
            <ff-navigation-item class="ff-nav-container" type="parent">
                <li class="ff-navigation-item parent-item">
                    <a class="ffw-nav-link" onclick="event.preventDefault()" href="{{__TARGET_URL__.url}}">
                        {{name}}
                    </a>
                </li>
            </ff-navigation-item>
        </ff-navigation>
    </ul>
</nav>

