<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
?>

<div class="ff-paging">
    <ff-paging unresolved>
        <ff-paging-set state="currentPage <= 3 && pageCount-currentPage < 3">
            <ff-paging-item type="previousLink">
                <input type="image" class="padd" src="<?= $escaper->escapeUrl($block->getViewFileUrl('Omikron_Factfinder::images/paging_prev_page.png')) ?>">
            </ff-paging-item>

            <ff-paging-item type="currentLink -2">{{page}}</ff-paging-item>
            <ff-paging-item type="currentLink -1">{{page}}</ff-paging-item>
            <ff-paging-item type="currentLink" style="font-weight: bold;">{{page}}</ff-paging-item>
            <ff-paging-item type="currentLink +1">{{page}}</ff-paging-item>
            <ff-paging-item type="currentLink +2">{{page}}</ff-paging-item>
            <ff-paging-item type="nextLink">
                <input type="image" class="padd" src="<?= $escaper->escapeUrl($block->getViewFileUrl('Omikron_Factfinder::images/paging_next_page.png')) ?>">
            </ff-paging-item>
        </ff-paging-set>

        <ff-paging-set state="currentPage <= 3 && pageCount-currentPage >= 3">
            <ff-paging-item type="previousLink">
                <input type="image" class="padd" src="<?= $escaper->escapeUrl($block->getViewFileUrl('Omikron_Factfinder::images/paging_prev_page.png')) ?>">
            </ff-paging-item>

            <ff-paging-item type="currentLink -2">{{value}}</ff-paging-item>
            <ff-paging-item type="currentLink -1">{{page}}</ff-paging-item>
            <ff-paging-item type="currentLink" style="font-weight: bold;">{{page}}</ff-paging-item>
            <ff-paging-item type="currentLink +1">{{page}}</ff-paging-item>
            ...
            <ff-paging-item type="lastLink">{{page}}</ff-paging-item>
            <ff-paging-item type="nextLink">
                <input type="image" class="padd" src="<?= $escaper->escapeUrl($block->getViewFileUrl('Omikron_Factfinder::images/paging_next_page.png')) ?>">
            </ff-paging-item>
        </ff-paging-set>

        <ff-paging-set state="currentPage > 3 && pageCount-currentPage >= 3">
            <ff-paging-item type="previousLink">
                <input type="image" class="padd" src="<?= $escaper->escapeUrl($block->getViewFileUrl('Omikron_Factfinder::images/paging_prev_page.png')) ?>">
            </ff-paging-item>

            <ff-paging-item type="firstLink">{{page}}</ff-paging-item>
            ...
            <ff-paging-item type="currentLink -1">{{page}}</ff-paging-item>
            <ff-paging-item type="currentLink" style="font-weight: bold;">{{page}}</ff-paging-item>
            <ff-paging-item type="currentLink +1">{{page}}</ff-paging-item>
            ...
            <ff-paging-item type="lastLink">{{page}}</ff-paging-item>

            <ff-paging-item type="nextLink">
                <input type="image" class="padd" src="<?= $escaper->escapeUrl($block->getViewFileUrl('Omikron_Factfinder::images/paging_next_page.png')) ?>">
            </ff-paging-item>
        </ff-paging-set>

        <ff-paging-set state="pageCount-currentPage < 3 && currentPage > 3">
            <ff-paging-item type="previousLink">
                <input type="image" class="padd" src="<?= $escaper->escapeUrl($block->getViewFileUrl('Omikron_Factfinder::images/paging_prev_page.png')) ?>">
            </ff-paging-item>
            <ff-paging-item type="firstLink">{{page}}</ff-paging-item>
            ...
            <ff-paging-item type="currentLink -1">{{page}}</ff-paging-item>
            <ff-paging-item type="currentLink" style="font-weight: bold;">{{page}}</ff-paging-item>
            <ff-paging-item type="currentLink +1">{{page}}</ff-paging-item>
            <ff-paging-item type="currentLink +2">{{page}}</ff-paging-item>

            <ff-paging-item type="nextLink">
                <input type="image" class="padd" src="<?= $escaper->escapeUrl($block->getViewFileUrl('Omikron_Factfinder::images/paging_next_page.png')) ?>">
            </ff-paging-item>
        </ff-paging-set>
    </ff-paging>
</div>
