<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<div class="search-wrapper">
    <div class="top-search-box">
        <ff-searchbox class="ff-searchbox" suggest-onfocus="true" use-suggest="true" select-onclick="true">
            <input class="input-text" placeholder="<?= $block->escapeHtmlAttr(__('Search…')) ?>"/>
            <ff-searchbutton>
                <button><span><?= $block->escapeHtml(__('Search…')) ?></span></button>
            </ff-searchbutton>
        </ff-searchbox>
    </div>
    <?= /* @noEscape */ $block->getChildHtml('suggest') ?>
</div>
