<?php
/** @var Magento\Framework\Escaper $escaper */
?>
<ff-suggest for-searchbox="ff-searchbox" layout="block" unresolved>
    <section id="searchContainer" class="searchTermContainer">
        <template data-role="popularSearches">
            <div class="popular-searches">
                <h3><?= $escaper->escapeHtmlAttr(__('Popular Searches')) ?></h3>
                <div data-template>{{name}}</div>
            </div>
        </template>

        <div data-container="searchTerm">
            <p class="containerCaption"><?= $escaper->escapeHtml(__('Search suggestions')) ?></p>
            <ff-suggest-item type="searchTerm">
                <span>{{{name}}}</span>
            </ff-suggest-item>
        </div>

        <div data-container="category">
            <p class="containerCaption"><?= $escaper->escapeHtml(__('Category suggestions')) ?></p>
            <ff-suggest-item type="category">
                <span>{{{name}}}</span>
            </ff-suggest-item>
        </div>

        <div data-container="brand">
            <p class="containerCaption"><?= $escaper->escapeHtml(__('Brands')) ?></p>
            <ff-suggest-item type="brand">
                <span>{{{name}}}</span>
            </ff-suggest-item>
        </div>
    </section>

    <section id="productContainer" class="productsContainer">
        <div data-container="productName">
            <p class="containerCaption"><?= $escaper->escapeHtml(__('Suggested products')) ?></p>
            <ff-suggest-item type="productName">
                <img data-image="{{suggestions.image}}" />
                <div class="product-center">
                    <div class="product-name">{{{name}}}</div>
                </div>
                <div class="product-right">
                    <div class="product-price">{{attributes.Price}}</div>
                </div>
            </ff-suggest-item>
        </div>
    </section>
</ff-suggest>
