<?php
/** @var $this \Omikron\Factfinder\Block\FF\ASN */
?>
<div class="ff-asn">
    <ff-asn unresolved>
        <ff-asn-group for-group="all" class="cursor">
            <ff-asn-group-element>
                <div data-selected>
                    <span class="filterCheckboxUnselected"><span class="filterCheckboxSelected"></span></span>
                    <span class="filterName">{{element.name}} {{group.unit}}</span>
                </div>
                <div data-unselected>
                    <span class="filterCheckboxUnselected"></span>
                    <span class="filterName">{{element.name}} {{group.unit}}</span>
                </div>
            </ff-asn-group-element>
        </ff-asn-group>
    </ff-asn>
</div>