<?php /** @var $block Magento\Framework\View\Element\Template */ ?>

<div class="ff-breadcrumb-trail">
    <span class="description"><?= $block->escapeHtml(__('Your Search for:')) ?></span>
    <ff-breadcrumb-trail unresolved>
        <!-- The search item is the content of the search query-->
        <ff-breadcrumb-trail-item type="search">
            <span>{{text}}</span>
        </ff-breadcrumb-trail-item>

        <!-- Filter items are set by the URL or over the ASN-->
        <ff-breadcrumb-trail-item type="filter">
            <span>{{text}}</span>
        </ff-breadcrumb-trail-item>

        <!-- Advisor items are included in the breadcrumb when an advisor-campaign is selected-->
        <ff-breadcrumb-trail-item type="advisor">
            <span>{{text}}</span>
        </ff-breadcrumb-trail-item>
    </ff-breadcrumb-trail>
    <ff-template scope="result" unresolved>
        <span style="padding-left: 15px"><?= $block->escapeHtml(__('produced {{resultCount}} Hits')) ?></span>
    </ff-template>
</div>
