<?php
/** @var $block Magento\Framework\View\Element\Template */
?>
<ff-campaign-advisor name="myadvisorcampaign" unresolved>
    <ff-campaign-advisor-question>
        <span>
            <h1 data-question>{{text}}</h1>
        </span>
        <div>
            <ff-campaign-advisor-answer>
                <div>
                    {{text}}
                </div>
            </ff-campaign-advisor-answer>
        </div>
    </ff-campaign-advisor-question>
</ff-campaign-advisor>
<ff-campaign-redirect></ff-campaign-redirect>
<ff-campaign-feedbacktext label="myfeedbackcampaign" unresolved>
    {{text}}
    <!--or mixed content-->
    <!--<div>{{text}}</div>-->
</ff-campaign-feedbacktext>
