<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Omikron\Factfinder\ViewModel\Communication $viewModel */
$viewModel  = $block->getViewModel();
$parameters = ((array) $block->getData('communication_parameters')) + $viewModel->getParameters();
?>

<script src="<?= $block->escapeUrl($block->getViewFileUrl('Omikron_Factfinder::ff-web-components/dist/vendor/custom-elements-es5-adapter.js')) ?>"></script>
<script src="<?= $block->escapeUrl($block->getViewFileUrl('Omikron_Factfinder::ff-web-components/dist/vendor/webcomponents-loader.js')) ?>"></script>
<script src="<?= $block->escapeUrl($block->getViewFileUrl('Omikron_Factfinder::ff-web-components/dist/bundle.js')) ?>" defer></script>

<ff-communication<?php foreach ($parameters as $key => $value) echo /** @noEscape */ sprintf(' %s="%s"', $key, $block->escapeHtmlAttr($value)) ?> />
<!-- Set FieldRoles -->
<script>
    document.addEventListener("ffReady", function () {
        factfinder.communication.fieldRoles = <?= /* @noEscape */ $viewModel->getFieldRoles() ?>;
    });
</script>
<div data-bind="scope: 'ffcommunication'"></div>
<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "ffcommunication": {
                            "component": "Omikron_Factfinder/js/view/ffcommunication"
                        }
                    }
                }
            }
        }
</script>
