<?php
/** @var $this \Omikron\Factfinder\Block\FF\Communication */
echo $this->getWebComponent(); ?>
<!-- Set FieldRoles -->
<script>
    document.addEventListener("ffReady", function () {
        factfinder.communication.fieldRoles =
        <?php echo $this->getFieldRoles(); ?>
        ;
    });
</script>
<div data-bind="scope: 'ffcommunication'">
    <script type="text/x-magento-init">
            {
                "*": {
                    "Magento_Ui/js/core/app": {
                        "components": {
                            "ffcommunication": {
                                "component": "Omikron_Factfinder/js/view/ffcommunication"
                            }
                        }
                    }
                }
            }
    </script>
</div>
<!-- Import WebComponents -->
<link rel="import" href="<?php echo $this->getViewFileUrl('Omikron_Factfinder::ff-web-components/dist/elements.build_with_dependencies.html'); ?>"/>