<?php
/** @var Magento\Framework\View\Element\Template $block  */
/** @var Omikron\Factfinder\ViewModel\Communication $viewModel */
$viewModel = $block->getViewModel();
$parameters = $viewModel->getParameters() + (array) $block->getData('communication_parameters');

echo '<ff-communication ' . implode(' ', array_map(
    function ($key, $value) { return sprintf("%s='%s'", $key, $value); },
    array_keys($parameters),
    $parameters
)) . '></ff-communication>'
?>


<!-- Set FieldRoles -->
<script>
    document.addEventListener("ffReady", function () {
        factfinder.communication.fieldRoles = <?= /* @noEscape */ $viewModel->getFieldRoles() ?>;
    });
</script>
<div data-bind="scope: 'ffcommunication'"></div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "ffcommunication": {
                        "component": "Omikron_Factfinder/js/view/ffcommunication"
                    }
                }
            }
        }
    }
</script>
<!-- Import WebComponents -->
<link rel="import" href="<?= $block->escapeUrl($block->getViewFileUrl('Omikron_Factfinder::ff-web-components/dist/elements.build_with_dependencies.html')) ?>"/>
