<?php /** @var $block \Omikron\Factfinder\Block\FF\RecordList */ ?>
<script type="text/x-magento-init">
    {
        ".product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": true
            }
        }
    }
</script>
<ff-record-list unresolved>
    <ff-record>
        <img data-image data-image-onerror="<?= $block->escapeUrl($block->getProductImagePlaceholder()) ?>" />
        <br/>
        <div class="recordContent">
            <div class="brand">{{record.Manufacturer}}</div>
            <a class="productDetailLink"
               data-redirect="{{record.ProductUrl}}" data-redirect-target="_blank" data-anchor="{{record.ProductUrl}}">
                {{{record.Name}}}
            </a>
            <div class="description">
                {{{record.Description}}}
            </div>
            <a class="toProduct" data-redirect="{{record.ProductUrl}}" data-redirect-target="_blank" data-anchor="{{record.ProductUrl}}">
                Product Page
            </a>
            <div class="productInfo">
                <?php if ($block->isAddToCartEnabled()): ?>
                    <div class="addCartLink basketIcon">
                        <form action="<?= $block->escapeUrl($block->getAddToCartUrl()) ?>" method="post" class="product_addtocart_form" novalidate="novalidate">
                            <input type="hidden" name="product" value="{{record.MagentoEntityId}}">
                            <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
                            <button data-track type="submit" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" class="action primary tocart">
                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                            </button>
                        </form>
                    </div>
                <?php endif; ?>
                <span class="price">{{record.Price}} <?= $block->escapeHtml($block->getCurrentCurrencySymbol()) ?> </span>
            </div>
        </div>
    </ff-record>
</ff-record-list>
