<?php
/** @var Magento\Framework\View\Element\Template $block */
?>
<div class="top-search-box">
    <ff-searchbox class="ff-searchbox" suggest-onfocus="true"
                  use-suggest="true"
                  select-onclick="true">
        <input placeholder="<?= $block->escapeHtml(__("Search...")) ?>"/>
    </ff-searchbox>

    <ff-searchbutton>
        <button><?= $block->escapeHtml(__("Search")) ?></button>
    </ff-searchbutton>
</div>
