<?php /** @var $block \Magento\Catalog\Block\Product\View */ ?>

<ff-similar-products record-id="<?= $block->escapeHtmlAttr($block->getProduct()->getSku()) ?>" unresolved>
    <div class="block upsell" data-limit="0" data-shuffle="0">
        <div class="block-title title">
            <strong id="block-upsell-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Similar Products')) ?></strong>
        </div>
        <div class="block-content content" aria-labelledby="block-upsell-heading">
            <div class="products wrapper grid products-grid products-upsell">
                <ol class="products list items product-items">
                    <ff-record-list>
                        <ff-record>
                            <li class="item product product-item" style="">
                                <div class="product-item-info ">
                                    <a href="{{record.ProductUrl}}" class="product photo product-item-photo">
                                        <span class="product-image-container">
                                            <span class="product-image-wrapper">
                                            <img class="product-image-photo" src="{{record.ImageUrl}}"
                                                 data-image="{{record.ImageUrl}}"
                                                 data-image-onerror="<?= $block->escapeUrl($block->getProductImagePlaceholder()) ?>"/>
                                            </span>
                                        </span>
                                    </a>
                                    <div class="product details product-item-details">
                                        <strong class="product name product-item-name"><a class="product-item-link"
                                                                                          title="Compete Track Tote"
                                                                                          href="{{record.ProductUrl}}">
                                                {{{record.Name}}}{{{record.Title}}}</a>
                                        </strong>
                                        <div class="price-box price-final_price" data-role="priceBox"
                                             data-product-id="{{record.MagentoEntityId}}">
                                            <span class="price-container price-final_price tax weee">
                                                <span id="product-price-{{record.MagentoEntityId}}"
                                                      data-price-amount="{{record.Price}}"
                                                      data-price-type="finalPrice" class="price-wrapper ">
                                                    <span class="price">{{record.Price}}<?= $block->escapeHtml($block->getCurrentCurrencySymbol()) ?></span>
                                                </span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ff-record>
                    </ff-record-list>
                </ol>
            </div>
        </div>
    </div>
</ff-similar-products>
