<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Omikron\Factfinder\ViewModel\Suggest $viewModel */
$viewModel = $block->getViewModel(); ?>
<div data-container="cms">
    <p class="containerCaption"><?= $block->escapeHtml(__('Pages')) ?></p>
    <?php if ($viewModel->useSeparateChannelForCms()): ?>
        <ff-suggest-item type="cms">
            <a href="{{attributes.deeplink}}" data-redirect="{{attributes.deeplink}}"
               data-redirect-target="_blank">
                <img data-image="{{{suggestions.image}}}">
                <div>
                    <span>{{name}}</span>
                    <div class="ff-suggest-cms-content">{{{attributes.content}}}</div>
                </div>
            </a>
        </ff-suggest-item>
    <?php else: ?>
        <ff-suggest-item type="cms">
            <a href="{{attributes.PageUrl}}" data-redirect="{{attributes.PageUrl}}"
               data-redirect-target="_blank">
                <img data-image="{{{attributes.PageImage}}}">
                <div>
                    <span>{{name}}</span>
                    <div class="ff-suggest-cms-content">{{{attributes.PageContent}}}</div>
                </div>
            </a>
        </ff-suggest-item>
    <?php endif; ?>
</div>
