<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
$categoryPath = (array) $block->getData('category_path');
//var_dump(json_encode($categoryPath)); die();
?>

<script>
    document.addEventListener(`ffCoreReady`, ({ factfinder }) => {
        factfinder.config.categoryPage = [
            factfinder.utils.filterBuilders.categoryFilter(`CategoryPath`, <?= /* @noEscape */ json_encode($categoryPath); ?>)
        ];

        factfinder.request.navigation({'filters': factfinder.config.categoryPage}, { requestOptions: { origin: `searchImmediately` } });
    });
</script>
