<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
$categoryPath = (array) $block->getData('category_path');
$categoryPathFieldName = $block->getData('category_path_field_name');
?>

<script>
    document.addEventListener(`ffCoreReady`, ({ factfinder, initialSearch }) => {
        factfinder.config.setAppConfig({
            categoryPage: [
                factfinder.utils.filterBuilders.categoryFilter('<?= /* @noEscape */ $categoryPathFieldName ?>', <?= /* @noEscape */ json_encode($categoryPath); ?>)
            ],
        });

        factfinder.routing.setUrlParamOptionsListener(() => ({
            blockFilters: [`<?= /* @noEscape */ $categoryPathFieldName ?>`],
        }));

        const initOptions = factfinder.config.get();
        initialSearch({
            filters: initOptions.appConfig.categoryPage,
        });
    });
</script>
