<script>
    document.addEventListener('ffReady', function (ff) {
        ff.eventAggregator.addBeforeHistoryPushCallback(function (res, event, url) {
            url = url.replace(/filter=CategoryPath[^&]+&?/, '').replace(/filterCategoryPathROOT[^&]+&?/g, '');
            ff.factfinder.communication.Util.pushParameterToHistory(res, url, event);
            return false;
        });
    });
</script>
