<?php /** @var Magento\Framework\View\Element\Template $block */ ?>

<script>
    document.addEventListener('ffReady', function (ff) {

        ff.resultDispatcher.addCallback("asn", function (asnData) {
            if (factfinder.communication.Util.isNg()) {
                asnData.splice(asnData.findIndex(function (element) {
                        return element.__associatedFieldNameV4 === '<?= $block->getData('category_path_field_name')?>'
                    }), 1)
            } else {
                const associatedFieldName = ff.factfinder.communication.Util.extractCategoryPathFieldName();

                asnData.splice(asnData.findIndex(function (group) {
                    return group.elements.every(function (element) {
                        return element.associatedFieldName === associatedFieldName;
                    });
                }), 1);
            }
        });
    });
</script>
