<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<script>
    require([
        'jquery'
    ], function (jQuery) {

        function enableCmsFeedButton() {
            Form.Element.enable('cms_feed_button');
            $('feed_button').removeClassName('disabled');
        }

        function disableCmsFeedButton() {
            Form.Element.disable('cms_feed_button');
            $('feed_button').addClassName('disabled');
        }

        jQuery('#cms_feed_button').click(function () {

            if ($('load_span_cms').hasClassName('no-display')) {
                $('load_span_cms').removeClassName('no-display');
                $('load_message_span_cms').update('<?= $block->escapeJs(__('Generating CMS export file')) ?>');
            }

            new Ajax.Request('<?= $block->escapeUrl($block->getUrl('factfinder/export/cmsfeed')) ?>', {
                parameters: {},
                loaderArea: false,
                asynchronous: true,
                onCreate: disableCmsFeedButton,
                onComplete: function (transport) {
                    var response = JSON.parse(transport.responseText);
                    $('load_message_span_cms').update(response.message);
                    $('load_spinner_cms').hide();
                    enableCmsFeedButton();
                }
            });
        });
    });
</script>

<?= /* @noEscape */ $block->getButtonHtml() ?>
<div class="sync-indicator no-display" id="load_span_cms">
    <img alt="Loading" id="load_spinner_cms" style="margin:0 5px" src="<?= $block->escapeUrl($block->getViewFileUrl('images/process_spinner.gif')) ?>"/>
    <span id="load_message_span_cms"></span>
</div>
