<script>
    require([
        'jquery'
    ], function(jQuery){

        function enableFeedButton() {
            Form.Element.enable('feed_button');
            $('feed_button').removeClassName('disabled');
        }

        function disableFeedButton() {
            Form.Element.disable('feed_button');
            $('feed_button').addClassName('disabled');
        }

        jQuery('#feed_button').click(function () {

            if ($('load_span').hasClassName('no-display')) {
                $('load_span').removeClassName('no-display');
                $('load_message_span').update('<?php echo __('Generating export file'); ?>');
            }

            new Ajax.Request('<?php echo $block->getUrl('factfinder/export/feed') ?>', {
                parameters:     {},
                loaderArea:     false,
                asynchronous:   true,

                onSuccess: function(transport) {
                    var response;

                    try {
                        response = JSON.parse(transport.responseText);

                        $('load_spinner').hide();
                        $('load_message_span').update(response.message);

                        enableFeedButton();
                    } catch (e) {
                        response = {};
                    }
                }
            });

            disableFeedButton();
        });
    });
</script>

<?php echo $block->getButtonHtml(); ?>
<div class="sync-indicator no-display" id="load_span">
    <img alt="Loading" id="load_spinner" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <span id="load_message_span"></span>
</div>
