<script>
    require([
        'jquery'
    ], function(jQuery){

        function enableButton() {
            Form.Element.enable('testconnection_button');
            $('testconnection_button').removeClassName('disabled');
        }

        function disableButton() {
            Form.Element.disable('testconnection_button');
            $('testconnection_button').addClassName('disabled');
        }

        jQuery('#testconnection_button').click(function () {

            if ($('ff_testconnection_load_span').hasClassName('no-display')) {
                $('ff_testconnection_load_span').removeClassName('no-display');
                $('ff_testconnection_load_message_span').update('<?php echo __('Testing connection...'); ?>');
            }

            new Ajax.Request('<?php echo $this->getUrl('factfinder/testconnection/testconnection') ?>', {
                parameters:     {},
                loaderArea:     false,
                asynchronous:   true,

                onSuccess: function(transport) {
                    var response;

                    try {
                        response = JSON.parse(transport.responseText);

                        $('ff_testconnection_load_spinner').hide();
                        $('ff_testconnection_load_message_span').update(response.message);

                        enableButton();
                    } catch (e) {
                        response = {};
                    }
                }
            });

            disableButton();
        });
    });
</script>

<?php echo $block->getButtonHtml(); ?>
<div class="sync-indicator no-display" id="ff_testconnection_load_span">
    <img alt="Loading" id="ff_testconnection_load_spinner" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <span id="ff_testconnection_load_message_span">

    </span>
</div>