<?php /** @var $block \Magento\Framework\View\Element\Template */?>
<script>
    require([
        'jquery'
    ], function(jQuery){

        function enableButton() {
            Form.Element.enable('testconnection_button');
            $('testconnection_button').removeClassName('disabled');
        }

        function disableButton() {
            Form.Element.disable('testconnection_button');
            $('testconnection_button').addClassName('disabled');
        }

        jQuery('#testconnection_button').click(function () {

            if ($('ff_testconnection_load_span').hasClassName('no-display')) {
                $('ff_testconnection_load_span').removeClassName('no-display');
                $('ff_testconnection_load_message_span').update('<?= $block->escapeJs(__('Testing connection…')) ?>');
            }

            new Ajax.Request('<?= $block->escapeJs($block->getUrl('factfinder/testconnection/testconnection')) ?>', {
                method: 'post',
                parameters: {
                    serverUrl: document.getElementById('factfinder_general_address').value,
                    channel: document.getElementById('factfinder_general_channel').value,
                    username: document.getElementById('factfinder_general_username').value,
                    password: document.getElementById('factfinder_general_password').value,
                    prefix: document.getElementById('factfinder_general_authentication_prefix').value,
                    postfix: document.getElementById('factfinder_general_authentication_postfix').value
                },
                loaderArea: false,
                asynchronous: true,
                onCreate: disableButton,
                onComplete: enableButton,
                onSuccess: function (transport) {
                    var response = JSON.parse(transport.responseText);
                    $('ff_testconnection_load_spinner').hide();
                    $('ff_testconnection_load_message_span').update(response.message);
                }
            });
        });
    });
</script>

<?= /* @noEscape */ $block->getButtonHtml() ?>
<div class="sync-indicator no-display" id="ff_testconnection_load_span">
    <img alt="Loading" id="ff_testconnection_load_spinner" style="margin:0 5px" src="<?= $block->escapeUrl($block->getViewFileUrl('images/process_spinner.gif')) ?>"/>
    <span id="ff_testconnection_load_message_span"></span>
</div>
