<?php
declare(strict_types=1);
return '{
   "records":[
      {
         "masterValues":{
            "Availability":"1",
            "Description":"The sporty Joust Duffle Bag cant be beat - not in the gym, not on the luggage carousel, not anywhere. Big enough to haul a basketball or soccer ball and some sneakers with plenty of room to spare, it is ideal for athletes with places to go. Dual top handles. Adjustable shoulder strap. Full-length zipper. L 29\" x W 13\" x H 11\".",
            "ImageUrl":"http:\/\/magento2.local\/media\/catalog\/product\/cache\/91f115788d6d7c0bc4f14236e3435aff\/m\/b\/mb01-blue-0.jpg",
            "Quantity":"Out of Stock",
            "HasVariants":0,
            "Name":"Joust Duffle Bag",
            "Master":"24-MB01",
            "CategoryPath":[
               [
                  "Gear"
               ],
               [
                  "Gear",
                  "Bags"
               ]
            ],
            "Price":34,
            "MagentoId":"1",
            "Eco Collection":[
               "No"
            ],
            "Deeplink":"http:\/\/magento2.4.local\/index.php\/joust-duffle-bag.html"
         },
         "variantValues":[
            {
               "ProductNumber":"24-MB01"
            }
         ],
         "id":"24-MB01",
         "score":100,
         "position":1,
         "foundWords":[

         ],
         "record":{
            "Availability":"1",
            "Description":"The sporty Joust Duffle Bag cant be beat - not in the gym, not on the luggage carousel, not anywhere . Big enough to haul a basketball or soccer ball and some sneakers with plenty of room to spare, its ideal for athletes with places to go. Dual top handles. Adjustable shoulder strap. Full-length zipper. L 29\" x W 13\" x H 11\".",
            "ImageUrl":"http:\/\/magento2.4.local\/media\/catalog\/product\/cache\/91f115788d6d7c0bc4f14236e3435aff\/m\/b\/mb01-blue-0.jpg",
            "Quantity":"Out of Stock",
            "HasVariants":0,
            "Name":"Joust Duffle Bag",
            "Master":"24-MB01",
            "CategoryPath":[
               [
                  "Gear"
               ],
               [
                  "Gear",
                  "Bags"
               ]
            ],
            "Price":"$34.00",
            "MagentoId":"1",
            "Eco Collection":[
               "No"
            ],
            "Deeplink":"http:\/\/magento2.4.local\/index.php\/joust-duffle-bag.html",
            "__ORIG_PRICE__":34
         }
      }
   ],
   "searchParams":{
      "query":"joust duffle bag",
      "channel":"magento24local",
      "customParameters":[
         {
            "name":"type",
            "values":[
               "search"
            ],
            "cacheIrrelevant":false
         }
      ]
   },
   "searchControlParams":{
      "useGeo":false
   },
   "breadCrumbTrail":[
      {
         "type":"search",
         "searchParams":{
            "query":"joust duffle bag",
            "channel":"magento24local",
            "customParameters":[
               {
                  "name":"type",
                  "values":[
                     "search"
                  ],
                  "cacheIrrelevant":false
               }
            ]
         },
         "text":"joust duffle bag",
         "value":"joust duffle bag"
      }
   ],
   "totalHits":1,
   "articleNumberSearch":true,
   "followSearch":"MC45OTk5OTk5OTk5OTk5OTk5",
   "scoreFirstHit":100,
   "scoreLastHit":100,
   "hits":[
      {
         "masterValues":{
            "Availability":"1",
            "Description":"The sporty Joust Duffle Bag cant be beat - not in the gym, not on the luggage carousel, not anywhere . Big enough to haul a basketball or soccer ball and some sneakers with plenty of room to spare, its ideal for athletes with places to go. Dual top handles. Adjustable shoulder strap. Full-length zipper. L 29\" x W 13\" x H 11\".",
            "ImageUrl":"http:\/\/magento2.4.local\/media\/catalog\/product\/cache\/91f115788d6d7c0bc4f14236e3435aff\/m\/b\/mb01-blue-0.jpg",
            "Quantity":"Out of Stock",
            "HasVariants":0,
            "Name":"Joust Duffle Bag",
            "Master":"24-MB01",
            "CategoryPath":[
               [
                  "Gear"
               ],
               [
                  "Gear",
                  "Bags"
               ]
            ],
            "Price":34,
            "MagentoId":"1",
            "Eco Collection":[
               "No"
            ],
            "Deeplink":"http:\/\/magento2.4.local\/index.php\/joust-duffle-bag.html"
         },
         "variantValues":[
            {
               "ProductNumber":"24-MB01"
            }
         ],
         "id":"24-MB01",
         "score":100,
         "position":1,
         "foundWords":[

         ]
      }
   ],
   "filters":[

   ],
   "answers":[

   ],
   "facets":[
      {
         "name":"CategoryPath",
         "elements":[

         ],
         "selectedElements":[
            {
               "text":"Gear",
               "totalHits":1,
               "searchParams":{
                  "query":"joust duffle bag",
                  "channel":"magento24local",
                  "followSearch":"MC45OTk5OTk5OTk5OTk5OTk5",
                  "customParameters":[
                     {
                        "name":"type",
                        "values":[
                           "search"
                        ],
                        "cacheIrrelevant":false
                     }
                  ]
               },
               "selected":"IMPLICIT",
               "clusterLevel":0
            },
            {
               "text":"Bags",
               "totalHits":1,
               "searchParams":{
                  "query":"joust duffle bag",
                  "filters":[
                     {
                        "name":"CategoryPath",
                        "values":[
                           {
                              "value":[
                                 "Gear"
                              ],
                              "type":"or",
                              "exclude":false
                           }
                        ],
                        "substring":false
                     }
                  ],
                  "channel":"magento24local",
                  "followSearch":"MC45OTk5OTk5OTk5OTk5OTk5",
                  "customParameters":[
                     {
                        "name":"type",
                        "values":[
                           "search"
                        ],
                        "cacheIrrelevant":false
                     }
                  ]
               },
               "selected":"IMPLICIT",
               "clusterLevel":1
            }
         ],
         "detailedLinks":5,
         "unit":"",
         "type":"CATEGORY_PATH",
         "showPreviewImages":false,
         "filterStyle":"TREE",
         "selectionType":"singleHideUnselected",
         "associatedFieldName":"CategoryPath"
      },
      {
         "name":"Price",
         "elements":[
            {
               "text":"[34.00 - 34.00]",
               "totalHits":0,
               "searchParams":{
                  "query":"joust duffle bag",
                  "channel":"magento24local",
                  "followSearch":"MC45OTk5OTk5OTk5OTk5OTk5",
                  "customParameters":[
                     {
                        "name":"type",
                        "values":[
                           "search"
                        ],
                        "cacheIrrelevant":false
                     }
                  ]
               },
               "selected":"FALSE",
               "clusterLevel":0,
               "absoluteMinValue":34,
               "absoluteMaxValue":34,
               "selectedMinValue":34,
               "selectedMaxValue":34
            }
         ],
         "selectedElements":[

         ],
         "detailedLinks":10,
         "unit":"\u20ac",
         "type":"FLOAT",
         "showPreviewImages":false,
         "filterStyle":"SLIDER",
         "selectionType":"singleHideUnselected",
         "associatedFieldName":"Price"
      }
   ],
   "paging":{
      "currentPage":1,
      "pageCount":1,
      "hitsPerPage":10,
      "defaultHitsPerPage":10
   },
   "tookTotal":13,
   "tookWorldmatch":1,
   "timedOut":false,
   "campaigns":[

   ],
   "fieldRoles":{
      "brand":"Manufacturer",
      "deeplink":"Deeplink",
      "description":"Description",
      "imageUrl":"ImageUrl",
      "masterId":"Master",
      "price":"Price",
      "productName":"Name",
      "productNumber":"ProductNumber"
   },
   "singleWordResults":[

   ],
   "sortItems":[
      {
         "order":"desc",
         "name":"Relevancy",
         "description":"sort.relevanceDescription",
         "searchParams":{
            "query":"joust duffle bag",
            "channel":"magento24local",
            "followSearch":"MC45OTk5OTk5OTk5OTk5OTk5",
            "customParameters":[
               {
                  "name":"type",
                  "values":[
                     "search"
                  ],
                  "cacheIrrelevant":false
               }
            ]
         },
         "selected":true
      },
      {
         "order":"asc",
         "name":"Name",
         "description":"sort.titleAsc",
         "searchParams":{
            "query":"joust duffle bag",
            "sortItems":[
               {
                  "order":"asc",
                  "name":"Name"
               }
            ],
            "channel":"magento24local",
            "followSearch":"MC45OTk5OTk5OTk5OTk5OTk5",
            "customParameters":[
               {
                  "name":"type",
                  "values":[
                     "search"
                  ],
                  "cacheIrrelevant":false
               }
            ]
         },
         "selected":false
      },
      {
         "order":"desc",
         "name":"Name",
         "description":"sort.titleDesc",
         "searchParams":{
            "query":"joust duffle bag",
            "sortItems":[
               {
                  "order":"desc",
                  "name":"Name"
               }
            ],
            "channel":"magento24local",
            "followSearch":"MC45OTk5OTk5OTk5OTk5OTk5",
            "customParameters":[
               {
                  "name":"type",
                  "values":[
                     "search"
                  ],
                  "cacheIrrelevant":false
               }
            ]
         },
         "selected":false
      },
      {
         "order":"asc",
         "name":"Price",
         "description":"sort.priceAsc",
         "searchParams":{
            "query":"joust duffle bag",
            "sortItems":[
               {
                  "order":"asc",
                  "name":"Price"
               }
            ],
            "channel":"magento24local",
            "followSearch":"MC45OTk5OTk5OTk5OTk5OTk5",
            "customParameters":[
               {
                  "name":"type",
                  "values":[
                     "search"
                  ],
                  "cacheIrrelevant":false
               }
            ]
         },
         "selected":false
      },
      {
         "order":"desc",
         "name":"Price",
         "description":"sort.priceDesc",
         "searchParams":{
            "query":"joust duffle bag",
            "sortItems":[
               {
                  "order":"desc",
                  "name":"Price"
               }
            ],
            "channel":"magento24local",
            "followSearch":"MC45OTk5OTk5OTk5OTk5OTk5",
            "customParameters":[
               {
                  "name":"type",
                  "values":[
                     "search"
                  ],
                  "cacheIrrelevant":false
               }
            ]
         },
         "selected":false
      }
   ],
   "geo":{
      "markets":[

      ],
      "selectedMarkets":[

      ],
      "showDistance":false
   }
}';
