<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<script>
    require([
        'jquery'
    ], function (jQuery) {

        function enableCmsFeedButton() {
            Form.Element.enable('cms_feed_button');
            $('cms_feed_button').removeClassName('disabled');
        }

        function disableCmsFeedButton() {
            Form.Element.disable('cms_feed_button');
            $('cms_feed_button').addClassName('disabled');
        }

        jQuery('#cms_feed_button').click(function () {

            if ($('cms_load_span').hasClassName('no-display')) {
                $('cms_load_span').removeClassName('no-display');
                $('cms_load_message_span').update('<?= $block->escapeJs(__('Generating CMS export file')) ?>');
            }

            new Ajax.Request('<?= $block->escapeUrl($block->getUrl('factfinder/export/cmsfeed')) ?>', {
                parameters: {},
                loaderArea: false,
                asynchronous: true,
                onCreate: disableCmsFeedButton,
                onComplete: function (transport) {
                    var response = JSON.parse(transport.responseText);
                    $('cms_load_message_span').update(response.message);
                    $('cms_load_spinner').hide();
                    enableCmsFeedButton();
                }
            });
        });
    });
</script>

<?= /* @noEscape */ $block->getButtonHtml() ?>
<div class="sync-indicator no-display" id="cms_load_span">
    <img alt="Loading" id="cms_load_spinner" style="margin:0 5px" src="<?= $block->escapeUrl($block->getViewFileUrl('images/process_spinner.gif')) ?>"/>
    <span id="cms_load_message_span"></span>
</div>
