<?php
/** @var Magento\Framework\View\Element\Template $block */
?>
<?= $block->getChildHtml() ?>
<script>
    document.addEventListener('ffCommunicationReady', function ({factfinder}) {
        const searchResult = {FF_SEARCH_RESULT};
        factfinder.communication.EventAggregator.currentSearchResult = searchResult;
        factfinder.communication.ResultDispatcher.dispatchRaw(searchResult);
    });
</script>
