---
name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4']
        deps: ['lowest', 'stable']
        exclude:
          - php: '7.4'
            deps: lowest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Load Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.deps }}-composer

      - name: Install dependencies
        run: |
          composer config --global --auth http-basic.repo.magento.com "${{ secrets.MAGENTO_USERNAME }}" "${{ secrets.MAGENTO_PASSWORD }}"
          composer config --global repositories.magento composer https://repo.magento.com/
          composer update --no-ansi --no-interaction --prefer-${{ matrix.deps }}

      - name: Run Static analysis
        - run: |
            vendor/bin/phpcs -nq .
            vendor/bin/phpmd src text phpmd.xml.dist

      - name: Run tests
        run: |
          vendor/bin/phpunit

